server:
  port: 8091
  
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greet-in:
          destination: baeldung
          contentType: application/json
        greet-out:
          destination: baeldung
          contentType: application/json

kafka:
    bootstrapAddress: localhost:9092
message:
    topic:
        name: baeldung
greeting:
    topic:
        name: greeting
filtered:
    topic:
        name: filtered
partitioned:
    topic:
        name: partitioned
